export type DocStatus = "available" | "beta" | "partial" | "in-progress" | "planned";
export type DocMode = "impara" | "usa" | "capisci";
export type DocRole = "socio" | "segreteria" | "amministratore" | "presidente" | "sviluppatore";
export interface DocPage { slug: string; title: string; description: string; category: string; mode: DocMode; roles: DocRole[]; status: DocStatus; lastReviewed: string; keywords: string[]; body: string; related?: string[]; }
const reviewed = "8 agosto 2026";
const make = (slug: string, title: string, category: string, mode: DocMode, statusOrRoles: DocStatus | DocRole[], rolesOrStatus: DocRole[] | DocStatus, body: string, related: string[] = []): DocPage => {
  const roles = Array.isArray(statusOrRoles) ? statusOrRoles : rolesOrStatus as DocRole[];
  const status = (Array.isArray(statusOrRoles) ? rolesOrStatus : statusOrRoles) as DocStatus;
  return { slug, title, description: body.split("\n")[0].replace(/^## /, ""), category, mode, roles, status, lastReviewed: reviewed, keywords: slug.split("/"), body, related };
};
const all = ["socio", "segreteria", "amministratore"] as DocRole[];
const staff = ["segreteria", "amministratore", "presidente"] as DocRole[];
const dev = ["amministratore", "sviluppatore"] as DocRole[];

export const docs: DocPage[] = [
  make("inizia/cose-abbo-docs", "Cos'è ABBO Docs", "Inizia qui", "impara", "available", all, "## In breve\n\nABBO Docs spiega APP SOCI con parole semplici e approfondimenti tecnici. Le etichette distinguono ciò che è disponibile, in sviluppo o previsto.\n\n## Tre modi di leggere\n\n**Impara** chiarisce i concetti. **Usa** accompagna nelle procedure. **Capisci** mostra cosa succede dietro le quinte.\n\nAPP SOCI è il gestionale associativo. ABBO Docs vive nel sito pubblico ABBO APS: sono due prodotti distinti.", ["inizia/cose-app-soci", "nfc/cose", "sicurezza/trasparenza-tecnologica"]),
  make("inizia/cose-app-soci", "Cos'è APP SOCI", "Inizia qui", "impara", "available", all, "## In breve\n\nAPP SOCI riunisce anagrafiche, tessere, ricevute, comunicazioni, eventi e funzioni economiche in una PWA.\n\n## Chi la usa\n\nIl socio consulta profilo, tessera e ricevute. La segreteria gestisce le attività quotidiane. Il direttivo è un gruppo destinatario: non ottiene automaticamente privilegi staff.", ["inizia/primo-accesso", "ruoli/ruoli", "economia/panoramica"]),
  make("inizia/ecosistema", "Come funziona l'ecosistema ABBO", "Inizia qui", "capisci", "available", [...all, "sviluppatore"], "## Il percorso\n\nABBO APS è il contesto associativo. APP SOCI gestisce i flussi autenticati. Il sito pubblico ospita informazioni e verifica NFC. Le API fanno da confine tra interfacce e dati.\n\nIl sito pubblico non accede direttamente alle tabelle del gestionale.\n\n~~~text\nSito pubblico → API pubblica → verifica server-side\nAPP SOCI → repository → dominio\n~~~", ["sviluppatore/architettura", "nfc/verifica-pubblica", "api/panoramica"]),
  make("inizia/primo-accesso", "Primo accesso", "Inizia qui", "usa", "partial", ["socio", "segreteria"], "## Prima di iniziare\n\nServe un account predisposto dall'associazione. Il flusso OTP e il secondo fattore per lo staff dipendono dall'ambiente.\n\n## Passaggi\n\n1. Apri APP SOCI.\n2. Completa l'installazione.\n3. Inserisci indirizzo e codice temporaneo.\n4. Completa il secondo fattore se richiesto.\n\nNon condividere il codice e non aggirare il gate.", ["pwa/iphone", "pwa/android", "faq/otp"]),
  make("inizia/glossario", "Glossario essenziale", "Inizia qui", "impara", "available", [...all, "sviluppatore"], "## Termini base\n\n**Socio** è la persona iscritta. **Volontario** presta attività e non ottiene automaticamente un account. La **quota** è annuale; la **card fisica** è separata.\n\n**NFC** è comunicazione a corto raggio. **PWA** è un sito installabile. **OTP** è un codice monouso. **AAL2** indica autenticazione più forte.", ["nfc/cose", "pwa/che-cose-una-pwa"]),
  make("soci/installazione", "Installare APP SOCI", "Per i soci", "usa", "available", ["socio"], "## Prima di iniziare\n\nUsa un browser aggiornato. L'installazione crea un accesso rapido: non è, da sola, una misura di sicurezza.\n\nApri il link ufficiale, segui il comando del browser e riapri l'app dalla schermata principale.", ["pwa/iphone", "pwa/android", "faq/installazione"]),
  make("soci/profilo", "Profilo e stato associativo", "Per i soci", "usa", "available", ["socio"], "## Cosa puoi vedere\n\nIl profilo mostra dati associativi, validità della tessera e card quando presente. Una tessera scaduta o sospesa blocca l'accesso.\n\nIl rinnovo della quota non genera una nuova card. Per correggere un dato, chiedi alla segreteria.", ["soci/tessera-digitale", "nfc/ciclo-di-vita"]),
  make("soci/tessera-digitale", "Tessera digitale", "Per i soci", "impara", "available", ["socio"], "## Una distinzione utile\n\nLa tessera digitale rappresenta la posizione associativa. La quota annuale ne determina la validità; la card fisica è separata.\n\nIl QR giornaliero cambia secondo Europe/Rome, non contiene dati personali leggibili e la semplice scansione non produce uno storico.", ["soci/qr", "nfc/cose", "sicurezza/protezione-dati"]),
  make("soci/qr", "QR della tessera", "Per i soci", "usa", "available", ["socio", "segreteria"], "## Come usarlo\n\nApri la tessera e mostra il QR allo staff. È temporale: non fotografarlo per riutilizzarlo.\n\nLo staff verifica firma, data e stato server-side. La verifica da sola non crea audit.", ["staff/scanner-qr", "faq/qr"]),
  make("soci/ricevute", "Le tue ricevute", "Per i soci", "usa", "available", ["socio"], "## In breve\n\nLe ricevute sono documenti associativi collegati a un versamento. Il numero è progressivo, annuale e non riutilizzabile.\n\nQuota associativa significa €15 annuali. Donazione è distinta. Una card fisica non è una ricevuta.", ["stampa/ciclo-ricevuta", "faq/ricevute"]),
  make("staff/panoramica", "Panoramica staff", "Per lo staff", "impara", "available", staff, "## Il lavoro quotidiano\n\nLo staff autorizzato lavora su soci, verifiche, ricevute e comunicazioni secondo il proprio ruolo. Le operazioni che cambiano dati devono essere esplicite e tracciabili.\n\nDirettivo è un gruppo destinatario, non una scorciatoia per privilegi staff.", ["ruoli/ruoli", "staff/scanner-qr"]),
  make("staff/scanner-qr", "Scanner QR", "Per lo staff", "usa", "available", ["segreteria", "amministratore"], "## Procedura\n\n1. Apri Scanner.\n2. Inquadra il QR giornaliero.\n3. Attendi la verifica server-side.\n4. Leggi stato, numero e scadenza.\n\nLa sola scansione non registra uno storico. Gli esiti non validi restano neutri.", ["soci/qr", "eventi/gestione"]),
  make("staff/procedure-ricevute", "Emettere una ricevuta", "Per lo staff", "usa", "available", ["segreteria", "amministratore"], "## Passaggi\n\n1. Apri Economia, Ricevute, Nuova ricevuta.\n2. Scegli socio, volontario, esterno o anonimo.\n3. Seleziona quota o donazione.\n4. Completa importo, data, luogo, metodo e consegna.\n5. Controlla e conferma.\n\nUn annullamento richiede motivazione: non si cancella né si riusa il numero.", ["stampa/ciclo-ricevuta", "economia/movimenti", "stampa/guida-template"]),
  make("staff/ricerca-destinatario", "Ricercare un destinatario", "Per lo staff", "usa", "available", ["segreteria", "amministratore"], "## Cerca con criterio\n\nInserisci almeno due caratteri e verifica l'identità con i dati mostrati. I risultati non mostrano codice fiscale o email completa.\n\nIl destinatario può essere socio, volontario, esterno o anonimo. Non copiare risultati in fogli locali.", ["staff/procedure-ricevute", "sicurezza/protezione-dati"]),
  make("ruoli/ruoli", "Ruoli e responsabilità", "Amministrazione", "impara", "available", staff, "## Principi\n\nIl socio gestisce la propria esperienza. La segreteria copre le operazioni quotidiane. L'amministrazione lavora su economia e registri secondo capability. Alcune azioni richiedono super-admin e secondo fattore.\n\nLa lente per ruolo è solo UX: non è autenticazione e non cambia i permessi reali.", ["amministrazione/libro-soci", "economia/panoramica"]),
  make("amministrazione/soci", "Gestire i soci", "Amministrazione", "usa", "available", staff, "## Creazione\n\nLo staff inserisce l'anagrafica e assegna il numero progressivo a partire da 0000. La tessera si attiva per un anno. Quota da €15 e ricevuta restano passaggi separati.\n\nIl rinnovo estende la validità e non crea una card fisica. Il prototipo non cancella record fisicamente.", ["amministrazione/libro-soci", "soci/profilo"]),
  make("amministrazione/libro-soci", "Libro Soci", "Amministrazione", "capisci", "partial", ["amministratore", "presidente"], "## Cosa documentiamo\n\nAPP SOCI prevede Registri per Libro Soci, Volontari e snapshot. È una vista amministrativa, non una pagina pubblica.\n\nL'esportazione del registro soci è riservata a super_admin. La fondazione è presente; la copertura operativa definitiva resta da verificare.", ["amministrazione/volontari", "ruoli/ruoli"]),
  make("amministrazione/volontari", "Registro volontari", "Amministrazione", "impara", "partial", staff, "## Volontario non significa socio\n\nUn volontario può essere occasionale o non occasionale, collegato a eventi e assicurazione. Non ottiene automaticamente un account APP SOCI.\n\nL'ammissione come socio è una decisione distinta, con numero e tessera propri.", ["amministrazione/libro-soci", "eventi/gestione"]),
  make("economia/panoramica", "Economia: la mappa", "Economia", "capisci", "partial", ["amministratore", "presidente"], "## La relazione\n\nUna ricevuta documenta un versamento; quando previsto, alimenta un movimento. I movimenti confluiscono in conti e cassa e contribuiscono al rendiconto.\n\n~~~text\nRicevuta → Movimento → Conto o cassa → Rendiconto\n~~~\n\nLe fondazioni sono presenti, ma alcuni passaggi sono in sviluppo.", ["economia/ricevute", "economia/movimenti", "amministrazione/rendiconto"]),
  make("economia/ricevute", "Ricevute e numerazione", "Economia", "capisci", ["segreteria", "amministratore"], "available", "## Due categorie\n\nQUOTA_ASSOCIATIVA è la quota annuale da €15. DONAZIONE è separata, con causale e documento propri.\n\nIl numero è progressivo, atomico, annuale e non riutilizzabile. Un annullamento mantiene documento e numero e richiede motivazione.", ["staff/procedure-ricevute", "economia/movimenti"]),
  make("economia/movimenti", "Movimenti, conti e cassa", "Economia", "capisci", ["amministratore", "presidente"], "in-progress", "## Cosa rappresenta un movimento\n\nUn movimento collega un'entrata o un'uscita a un conto o alla cassa. Non sostituisce la ricevuta.\n\nUI e migrazioni di fondazione sono presenti; riconciliazione, migrazione dati e controllo end-to-end restano in sviluppo.", ["economia/panoramica", "economia/esercizi"]),
  make("economia/esercizi", "Esercizi finanziari", "Economia", "impara", ["amministratore", "presidente"], "in-progress", "## Un esercizio è un perimetro\n\nRaccoglie movimenti e report di un periodo definito. La numerazione annuale delle ricevute e l'anno di una card non sono la stessa cosa.\n\nLa procedura completa di chiusura deve essere verificata con il referente amministrativo.", ["amministrazione/rendiconto", "economia/movimenti"]),
  make("amministrazione/rendiconto", "Rendiconto ETS", "Economia", "impara", ["amministratore", "presidente"], "planned", "## Stato\n\nLa documentazione prevede rendiconto ETS e modelli D/E, ma la procedura completa non è ancora una funzione verificata nell'app.\n\nUn report deve riflettere periodo, categorie e responsabilità approvate.", ["economia/panoramica", "economia/esercizi"]),
  make("nfc/cose", "Cos'è una tessera NFC", "Tessera NFC", "impara", [...all, "sviluppatore"], "available", "## La distinzione fondamentale\n\nLa card fisica non scade automaticamente. L'anno identifica l'edizione. La quota annuale riguarda la posizione e non genera una nuova card al rinnovo.\n\nIl token NFC è casuale e separato dal codice visibile, come ABBO-0001. Il codice visibile non è un autenticatore.", ["nfc/ciclo-di-vita", "nfc/verifica-pubblica"]),
  make("nfc/ciclo-di-vita", "Ciclo di vita della card", "Tessera NFC", "capisci", ["segreteria", "amministratore", "sviluppatore"], "available", "## Il ciclo\n\n~~~text\nRichiesta → assegnazione → programmazione → verifica\n                         ↘ revoca o sostituzione\n~~~\n\nLa card ordinaria richiede una donazione associata di almeno €50; per il direttivo esiste un'esenzione esplicita. Il token raw è mostrato una sola volta; il gestionale conserva il digest.", ["nfc/programmazione", "nfc/smarrimento", "nfc/verifica-pubblica"]),
  make("nfc/programmazione", "Programmare il tag", "Tessera NFC", "usa", ["segreteria", "amministratore"], "partial", "## Passaggi\n\n1. Usa il link restituito dall'assegnazione.\n2. Scrivilo nel tag.\n3. Verifica con un dispositivo di test.\n4. Se previsto, blocca il tag in sola lettura.\n\nNon copiare il link in log o screenshot condivisi. La procedura hardware definitiva dipende dal dispositivo approvato.", ["nfc/verifica-pubblica", "nfc/smarrimento"]),
  make("nfc/verifica-pubblica", "Verifica pubblica", "Tessera NFC", "capisci", ["socio", "sviluppatore", "segreteria"], "partial", "## Il flusso previsto\n\n~~~text\nTag NFC → sito pubblico → POST /api/v1/membership-cards/verify → risposta minima\n~~~\n\nIl browser legge il fragment in memoria, non persiste il token e prova a rimuoverlo dall'URL. La verifica distingue card valida, quota non attiva, posizione sospesa, card non valida ed errore temporaneo.\n\nIl client API è presente nel repository del sito; l'integrazione della route membership-card nel bundle principale resta da completare.", ["api/membership-card-verify", "sicurezza/nfc"]),
  make("nfc/smarrimento", "Smarrimento e sostituzione", "Tessera NFC", "usa", ["socio", "segreteria", "amministratore"], "partial", "## Segnala subito\n\nContatta la segreteria indicando il problema, non il token. Lo staff autorizzato può revocare la card e avviare una sostituzione.\n\nIl vecchio token non deve più risultare verificabile. Non tentare di recuperare il link da cronologia o screenshot.", ["nfc/ciclo-di-vita", "nfc/verifica-pubblica"]),
  make("nfc/edizione", "Nuova edizione", "Tessera NFC", "impara", ["amministratore", "segreteria"], "available", "## Un anno, una edizione\n\nL'anno identifica l'edizione della card fisica. Una nuova quota non genera automaticamente una nuova card.\n\nUn codice come ABBO-2026-0042 riconosce una card, ma non è il token NFC e non autentica nessuno.", ["nfc/cose", "soci/tessera-digitale"]),
  make("api/panoramica", "Panoramica API pubblica", "Per sviluppatori", "capisci", ["sviluppatore"], "partial", "## Regola default-deny\n\nLa documentazione elenca solo il contratto pensato per terzi. Funzioni amministrative, RPC e operazioni server-side restano fuori.\n\nABBO Docs mostra esempi statici e una simulazione: non invia token arbitrari all'API di produzione.", ["api/membership-card-verify", "api/errori"]),
  make("api/membership-card-verify", "Public card verification", "Per sviluppatori", "capisci", ["sviluppatore"], "partial", "## Endpoint\n\n~~~http\nPOST /api/v1/membership-cards/verify\nContent-Type: application/json\nx-abbo-api-version: v1\n~~~\n\nRequest di esempio:\n~~~json\n{ token: TOKEN_DI_ESEMPIO }\n~~~\n\nLa risposta è minima: esito, codice card e dati necessari. Non include email, codice fiscale o identificativi tecnici.", ["api/errori", "nfc/verifica-pubblica"]),
  make("api/errori", "Errori e cache policy", "Per sviluppatori", "usa", ["sviluppatore"], "partial", "## Stati concettuali\n\nactive è card valida; membership_inactive è quota non attiva; suspended è posizione sospesa; not_valid è card non verificabile; unavailable è problema temporaneo.\n\nUsa HTTPS, POST, credentials omit, no-store e un timeout. Non trasformare gli errori in un enumeratore.", ["api/membership-card-verify", "nfc/verifica-pubblica"]),
  make("pwa/che-cose-una-pwa", "Perché una PWA", "PWA", "impara", ["socio", "segreteria"], "available", "## Una PWA è un sito installabile\n\nAPP SOCI usa il browser senza richiedere necessariamente uno store. Account e permessi restano server-side.\n\nLa cache statica può aiutare l'apertura; non significa che dati autenticati o verifiche NFC siano disponibili offline.", ["pwa/iphone", "pwa/android"]),
  make("pwa/iphone", "Installare su iPhone", "PWA", "usa", ["socio"], "available", "## Passaggi\n\n1. Apri APP SOCI in Safari.\n2. Tocca Condividi.\n3. Scegli Aggiungi alla schermata Home.\n4. Conferma e riapri.\n\nL'installazione non sostituisce l'OTP.", ["pwa/che-cose-una-pwa", "faq/installazione"]),
  make("pwa/android", "Installare su Android", "PWA", "usa", ["socio"], "available", "## Passaggi\n\n1. Apri APP SOCI nel browser aggiornato.\n2. Apri il menu.\n3. Scegli Installa app o Aggiungi alla schermata Home.\n4. Conferma.\n\nSe il gate resta bloccato, non aggirarlo.", ["pwa/che-cose-una-pwa", "faq/installazione"]),
  make("stampa/ciclo-ricevuta", "Dal versamento al documento", "Stampa e documenti", "capisci", ["segreteria", "amministratore"], "available", "## Il ciclo\n\n~~~text\nBozza → emissione → numero assegnato → documento cristallizzato\n      → app / email / stampa → archivio\n~~~\n\nLa stampa non modifica la ricevuta, non assegna numeri e non crea movimenti. Un reinvio non è una nuova emissione.", ["stampa/formati", "stampa/guida-template"]),
  make("stampa/formati", "A4, 58 mm e 80 mm", "Stampa e documenti", "usa", ["segreteria", "amministratore"], "partial", "## 58 mm\n\nIl profilo usa anteprima e dialogo del browser: APP SOCI, BrowserPrintAdapter, dialogo, driver, stampante. Non è controllo USB diretto.\n\nI profili A4 e 80 mm sono predisposti ma non vanno presentati come completamente implementati.", ["stampa/ciclo-ricevuta", "stampa/guida-template"]),
  make("stampa/guida-template", "Creare un template di ricevuta", "Stampa e documenti", "capisci", ["amministratore", "sviluppatore"], "partial", "## La formula\n\n~~~text\nPDF base + manifest + dati ricevuta = documento finale\n~~~\n\nOgni campo dinamico ha nome, tipo, formato, obbligatorietà e comportamento overflow. Non usare dati reali o URL interni.", ["stampa/ciclo-ricevuta", "sicurezza/protezione-dati"]),
  make("sicurezza/protezione-dati", "Come proteggiamo i dati", "Sicurezza e privacy", "impara", [...all, "sviluppatore"], "available", "## Principi\n\nAPP SOCI è progettata attorno a minimizzazione, accesso per ruolo, cifratura in transito, documenti privati e audit delle azioni amministrative.\n\nQuesta pagina non dichiara conformità automatica, sicurezza assoluta o certificazioni. Non sostituisce l'informativa privacy.", ["sicurezza/nfc", "sicurezza/trasparenza-tecnologica"]),
  make("sicurezza/nfc", "Privacy della tessera NFC", "Sicurezza e privacy", "capisci", [...all, "sviluppatore"], "available", "## La verifica pubblica\n\nIl browser legge il token in memoria e lo invia via HTTPS all'API pubblica. Il sito non accede direttamente al database e la scansione non produce uno storico.\n\nIl token è casuale; il codice stampato è pubblico e non autentica. Una card può essere copiata: l'affidabilità dipende dalla verifica server-side e dalle procedure fisiche.", ["nfc/verifica-pubblica", "nfc/smarrimento"]),
  make("sicurezza/trasparenza-tecnologica", "Trasparenza tecnologica", "Sicurezza e privacy", "impara", all, "available", "## In linguaggio umano\n\nAPP SOCI usa i dati necessari per account, posizione associativa, ricevute e comunicazioni. Il sito pubblico usa dati pubblici e una richiesta minima per la card NFC.\n\nIl token viene consumato in memoria e non salvato in localStorage o sessionStorage.", ["sicurezza/protezione-dati", "nfc/verifica-pubblica"]),
  make("faq/otp", "Non ricevo il codice OTP", "Riferimenti", "usa", ["socio", "segreteria"], "available", "## Controlla\n\nVerifica indirizzo, spam e connessione. Attendi prima di chiedere un nuovo codice. Non condividere OTP ricevuti per errore.\n\nSe continua, contatta la segreteria con orario e dispositivo, senza inviare il codice.", ["inizia/primo-accesso"]),
  make("faq/installazione", "Non riesco a installare la PWA", "Riferimenti", "usa", ["socio"], "available", "## Prova così\n\nUsa Safari su iPhone o un browser aggiornato su Android. Apri il link ufficiale e cerca il comando nel menu. Se il login è bloccato, il problema riguarda l'accesso e non va aggirato.", ["pwa/iphone", "pwa/android"]),
  make("faq/qr", "Il QR non viene letto", "Riferimenti", "usa", ["socio", "segreteria"], "available", "## Prove rapide\n\nAumenta la luminosità, evita riflessi e riapri la tessera per ottenere il codice del giorno. Se l'esito non è valido, chiedi alla segreteria di verificare lo stato.", ["soci/qr", "staff/scanner-qr"]),
  make("faq/nfc", "La card NFC non viene verificata", "Riferimenti", "usa", ["socio", "segreteria"], "partial", "## Prima prova\n\nControlla NFC, avvicina il telefono al tag e usa una connessione affidabile. Se mostra errore temporaneo, riprova più tardi. Non incollare il token in chat o screenshot.", ["nfc/verifica-pubblica", "nfc/smarrimento"]),
  make("faq/ricevute", "Non vedo una ricevuta", "Riferimenti", "usa", ["socio", "segreteria"], "available", "## Controlla\n\nVerifica account e versamento: la creazione del socio non genera da sola una ricevuta. Per un reinvio, chiedi alla segreteria: ristampare non significa creare un nuovo numero.", ["soci/ricevute", "staff/procedure-ricevute"]),
  make("faq/stampa", "La stampante non stampa bene", "Riferimenti", "usa", ["segreteria", "amministratore"], "partial", "## Controlla il profilo\n\nScegli il formato corretto e il driver del sistema operativo. Per 58 mm usa il dialogo del browser e controlla l'anteprima. Segnala formato, browser e stampante senza modificare il numero.", ["stampa/formati", "stampa/guida-template"]),
  make("eventi/gestione", "Eventi e comunicazioni", "Per lo staff", "impara", ["segreteria", "amministratore"], "partial", "## A cosa servono\n\nEventi e comunicazioni informano soci e volontari. Non sostituiscono la verifica di una tessera e non concedono permessi. Notifiche e preferenze non devono contenere token, segreti o dati eccedenti.", ["staff/panoramica", "amministrazione/volontari"]),
  make("sviluppatore/architettura", "Dentro APP SOCI", "Per sviluppatori", "capisci", "available", ["sviluppatore"], "## Le macro-aree\n\n- src/domain: tipi e regole pure;\n- src/data: repository e contratti;\n- src/pages: interfaccia;\n- supabase: migrazioni, funzioni e test;\n- scripts: validazioni;\n- docs: decisioni e requisiti.\n\nLe pagine non devono conoscere direttamente Supabase. Non pubblichiamo schema completo, RLS, segreti o host interni.", ["sviluppatore/code-atlas", "api/panoramica"]),
  make("sviluppatore/code-atlas", "APP SOCI Code Atlas", "Per sviluppatori", "capisci", "available", ["sviluppatore"], "## La catena\n\n~~~text\nUI → servizi e repository → API/Edge Functions → RPC → database\n~~~\n\nUna regola di dominio appartiene a src/domain; un accesso dati al repository; una policy server-side non si sposta nel client.", ["sviluppatore/architettura", "ruoli/ruoli"]),
  make("riferimenti/changelog", "Changelog pubblico", "Riferimenti", "impara", "available", ["socio", "segreteria", "sviluppatore"], "## 8 agosto 2026\n\n- Nasce ABBO Docs con Impara, Usa e Capisci.\n- Aggiunte mappe, tour, role lens e simulatore NFC.\n- Pubblicati contenuti redatti su APP SOCI, ricevute, economia, PWA e privacy.\n\nGli aggiornamenti di sicurezza non vengono dettagliati quando aumenterebbero la superficie d'attacco.", ["inizia/cose-abbo-docs", "riferimenti/stato-funzionalita"]),
  make("riferimenti/stato-funzionalita", "Stato delle funzionalità", "Riferimenti", "capisci", "available", [...all, "sviluppatore"], "## Le etichette\n\n**Disponibile** è verificato. **Beta** è utilizzabile ma soggetto a revisione. **In sviluppo** ha fondazioni o UI non complete. **Previsto** è una direzione, non una promessa di rilascio.\n\nUna documentazione affidabile deve dire anche cosa non è ancora pronto.", ["riferimenti/changelog", "economia/panoramica", "nfc/verifica-pubblica"]),
];
export const docBySlug = new Map(docs.map((doc) => [doc.slug, doc]));
export const categoryOrder = ["Inizia qui", "Per i soci", "Per lo staff", "Amministrazione", "Economia", "Tessera NFC", "Per sviluppatori", "PWA", "Stampa e documenti", "Sicurezza e privacy", "Riferimenti"];
export const modeLabels: Record<DocMode, { label: string; eyebrow: string; description: string }> = { impara: { label: "Impara", eyebrow: "Parti dai concetti", description: "Capisci il perché prima di fare il passo successivo." }, usa: { label: "Usa", eyebrow: "Vai al pratico", description: "Procedure brevi, con un risultato chiaro." }, capisci: { label: "Capisci", eyebrow: "Apri il cofano", description: "Architettura e flussi senza dettagli sensibili." } };
export const statusLabels: Record<DocStatus, string> = { available: "Disponibile", beta: "Beta", partial: "Parziale", "in-progress": "In sviluppo", planned: "Previsto" };
